version: "3"
services: 
  mongodb: 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - todo-data:/data/db
    container_name: mongodb
    networks:
      - todo-network
  api:
    build: 
      context: ./services/api
      dockerfile: Dockerfile.test-front
    ports:
      - 3001:3001
    container_name: todo-api
    environment:
      - NODE_ENV=test
      - DATABASE_NAME=todoapp-test
      - DATABASE_URL=mongodb
    depends_on:
      - mongodb
    networks:
      - todo-network

  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: todo-web
    stdin_open: true
    links:
      - api
    networks:
      - todo-network

  web-test:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.test
    container_name: todo-web-test
    depends_on: 
      - web
    networks:
      - todo-network

volumes:  
  todo-data:

networks:
  todo-network:
    driver: bridge