version: "3"
services: 
  mongo: 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - todo-data:/data/db
    networks:
      - todo-network
  api:
    build: 
      context: ./services/api
      dockerfile: Dockerfile.test2
    ports:
      - 3001:3001
    container_name: todo-api
    environment:
      - NODE_ENV=test
      - DATABASE_NAME=todoapp-test
      - DATABASE_URL=localhost:27017
    depends_on:
      - mongo
    env_file: .env
    networks:
      - todo-network

volumes:  
  todo-data:

networks:
  todo-network:
    driver: bridge