version: "3.7"

services: 
  mongo: 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - todo-data:/data/db
    env_file: .env
    networks:
      - todo-network
  api:
    build: karakocberkay/todo_api
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      - mongo
    networks:
      - todo-network
  web:
    build: karakocberkay/todo_web
    ports:
      - 3000:3000
    stdin_open: true
    links:
      - api
    networks:
      - todo-network

volumes:  
  todo-data:

networks:
  todo-network: