version: "3"
services: 
  mongo: 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - todo-data:/data/db
    networks:
      - todo-network
  api:
    build: ./services/api
    ports:
      - 3001:3001
    container_name: todo-api
    depends_on:
      - mongo
    env_file: .env
    networks:
      - todo-network

  web:
    build: ./services/web
    ports:
      - 3000:3000
    container_name: todo-web
    stdin_open: true
    links:
      - api
    networks:
      - todo-network

volumes:  
  todo-data:

networks:
  todo-network:
    driver: bridge