version: "3"
services:
    web-test:
        build:
        context: ./services/web
        dockerfile: Dockerfile.test
        container_name: todo-web-test
        depends_on:
            - web
        networks:
            - todo-network

networks:
    todo-network:
        driver: bridge
