image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

stages:
  - test_front
  - test_back
  - dockerize
  - deploy
  
test_front:
  stage: test_front
  scripts:
    - docker-compose -f docker-compose.test-front.yml up
   
test_back:
  stage: test_back
  scripts:
    - docker-compose -f docker-compose.test-back.yml up
   
dockerize:
  stage: dockerize
  scripts:
    - docker-compose -f docker-compose.yml up
    
deploy:
  stage: deploy
  scripts:
    - echo "deploy stage"
