image: node:latest

services:
  - mongo:latest

front_test:
  script:
  - echo "Running test for frontend"
  - cd services/api
  - npm install
  - npm start
  - cd ..
  - cd ..
  - cd services/web
  - npm install
  - npm test
  - echo "Test for frontend completed"
backend_test:
  script:
  - echo "Running tests for backend"
  - cd services/api
  - npm install
  - npm test
  - echo "Test for backend completed"
dockerize:
  image: docker:latest
  script:
  - echo "Dockerizing"
  - docker-compose build
  - echo "Dockerizing completed"
deploy:
  stage: deploy
  script:
  - echo "Deploying"
